* Description

    *ScrapDict* is dedicated to add more structuring to *ScrapBook* (Firefox extension at [[https://addons.mozilla.org/uk/firefox/addon/scrapbook/]] ). So instead of a list, it could be represented in a *Freemind* way ( [[http://freemind.sourceforge.net/wiki/index.php/Main_Page]] )

    It relies on user tags, which should be added to the *ScrapBook* page comment section. Each tag should start from *#* sign, full line is treated as tag. Tag can contain spaces.

* Usage

    Find *ScrapBook* data directory (e.g. ~/.mozilla/firefox/xxxxxxx.default/ScrapBook/data/), then run

#+BEGIN_EXAMPLE
    path/to/ScapDict/scripts/scrapdict -s /path/to/scrapbook/data_directory -d /path/to/freemind.mm
#+END_EXAMPLE 

* Versions

    Should work for linux. If you would like to test/adapt it for e.g. Windows - be my guest.

    I took versions I have locally, so this is mostly for myself, however if you will find it useful - nice :). Write me if you have some problems there.
    I do know about new *Freemind* v1.0.0, not tested it. So if you happen to try it out, tell me.

* TODO

- [ ] *ScrapDict version 0.2* milestone
    - [ ] *Epic* section becomes bigger, but to make it useful, add neighboring tags as sub tags
    - [ ] *Tags Desert* contains to many of tags, as expected, separate content, creating nodes with name representing number of pages, as well as fold them off
    - [ ] Update *README* file
- [O] *ScrapDict version 0.1* milestone
    - [X] Add common *ScrapBook v1.5.14* support
    - [X] Add *Freemind v0.9.0* export
    - [X] Add command line arguments parser
        - [X] Add ScrapBook version
        - [X] Add Freemind version
        - [X] Add ScrapBook data source directory
        - [X] Add Freemind output file
        - [X] Add help
        - [X] Add list of supported versions
    - [X] *ScrapBook parser* should support comments without tags, moving them to *#Tagless* section
    - [X] Add *Freemind #ByDate* section, containing *#datetime* tags for all of the history
    - [X] Add *Freemind #Recent* section, containing *#datetime* tags for *last 7 days*
    - [X] Provide fast access to index file, so e.g. tagless could become tagful
    - [X] Provide additional links to pdf files
    - [X] Provide additional link to source site
    - [X] Sort tags within the sections
    - [ ] Add Tests for *ScrapBook parser*
    - [ ] Update *README* file
    - [X] Bugs
        - [X] Nothing
